deepfm:
  dnn_hidden_units: [768, 384, 64]
  dnn_activation: "relu"
  fm_embed_dim: 64
  seed: 1024
  linear_feature_columns_name: 
    - "expose_pos"
    - "expose_hourdiff"
    - "expose_hour"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "userid_history_duration_mean"
    - "userid_history_count"
    - "userid_expose_count"
    - "userid_ctr"
    - "docid_history_duration_mean"
    - "docid_history_count"
    - "docid_expose_count"
    - "docid_ctr"
    - "category1_ctr"
    - "category1_popularity"
    - "category1_history_duration_mean"
    - "category2_ctr"
    - "category2_popularity"
    - "category2_history_duration_mean"
    - "userid_category1_history_count"
    - "userid_category1_ctr"
    - "userid_category1_history_duration_mean"
    - "userid_category2_history_count"
    - "userid_category2_ctr"
    - "userid_category2_history_duration_mean"
  dnn_feature_columns_name:
    - "expose_hourdiff"
    - "user_id"
    - "device_name"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "userid_history_duration_mean"
    - "userid_history_count"
    - "userid_expose_count"
    - "userid_ctr"
    - "article_id"
    - "keywords"
    - "image_count"
    - "doc_title_embed"
    - "docid_history_duration_mean"
    - "docid_history_count"
    - "docid_expose_count"
    - "docid_ctr"
    - "category_level1"
    - "category1_ctr"
    - "category1_popularity"
    - "category_level2"
    - "category1_history_duration_mean"
    - "category2_ctr"
    - "category2_popularity"
    - "category2_history_duration_mean"
    - "expose_hour"
    - "network_env"
    - "refresh_count"
    - "userid_category1_history_count"
    - "userid_category1_ctr"
    - "userid_category1_history_duration_mean"
    - "userid_category2_history_count"
    - "userid_category2_ctr"
    - "userid_category2_history_duration_mean"
esmm:
  num_tasks: 2
  tasks: ["binary", "binary"]
  tasks_name: ["ctr","cvr"]
  fm_embed_dim: 18
  num_experts: 3
  units_experts: 512
  task_dnn_units: [360, 200, 80]
  seed: 1024
  dnn_activation: 'relu'
  linear_feature_columns_name:
    - "expose_pos"
    - "expose_hourdiff"
    - "expose_hour"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "userid_history_duration_mean"
    - "userid_history_count"
    - "userid_expose_count"
    - "userid_ctr"
    - "docid_history_duration_mean"
    - "docid_history_count"
    - "docid_expose_count"
    - "docid_ctr"
    - "category1_ctr"
    - "category1_popularity"
    - "category1_history_duration_mean"
    - "category2_ctr"
    - "category2_popularity"
    - "category2_history_duration_mean"
    - "userid_category1_history_count"
    - "userid_category1_ctr"
    - "userid_category1_history_duration_mean"
    - "userid_category2_history_count"
    - "userid_category2_ctr"
    - "userid_category2_history_duration_mean"
  fm_cross_columns_name:
    - "expose_hour"
    - "expose_hourdiff"
    - "network_env"
    - "refresh_count"
    - "user_id"
    - "device_name"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "article_id"
    - "keywords"
    - "image_count"
    - "category_level1"
    - "category_level2"
    - "userid_category1_history_count"
    - "userid_category2_history_count"
  dnn_feature_columns_name:
    - "expose_hourdiff"
    - "user_id"
    - "device_name"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "userid_history_duration_mean"
    - "userid_history_count"
    - "userid_expose_count"
    - "userid_ctr"
    - "article_id"
    - "keywords"
    - "image_count"
    - "doc_title_embed"
    - "docid_history_duration_mean"
    - "docid_history_count"
    - "docid_expose_count"
    - "docid_ctr"
    - "category_level1"
    - "category1_ctr"
    - "category1_popularity"
    - "category_level2"
    - "category1_history_duration_mean"
    - "category2_ctr"
    - "category2_popularity"
    - "category2_history_duration_mean"
    - "expose_hour"
    - "network_env"
    - "refresh_count"
    - "userid_category1_history_count"
    - "userid_category1_ctr"
    - "userid_category1_history_duration_mean"
    - "userid_category2_history_count"
    - "userid_category2_ctr"
    - "userid_category2_history_duration_mean"
deepfm_lhuc:
  dnn_hidden_units: [768, 384, 64]
  dnn_activation: "relu"
  fm_embed_dim: 64
  seed: 1024
  linear_feature_columns_name: 
    - "expose_pos"
    - "expose_hourdiff"
    - "expose_hour"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "userid_history_duration_mean"
    - "userid_history_count"
    - "userid_expose_count"
    - "userid_ctr"
    - "docid_history_duration_mean"
    - "docid_history_count"
    - "docid_expose_count"
    - "docid_ctr"
    - "category1_ctr"
    - "category1_popularity"
    - "category1_history_duration_mean"
    - "category2_ctr"
    - "category2_popularity"
    - "category2_history_duration_mean"
    - "userid_category1_history_count"
    - "userid_category1_ctr"
    - "userid_category1_history_duration_mean"
    - "userid_category2_history_count"
    - "userid_category2_ctr"
    - "userid_category2_history_duration_mean"
  dnn_feature_columns_name:
    - "expose_hourdiff"
    - "user_id"
    - "device_name"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "userid_history_duration_mean"
    - "userid_history_count"
    - "userid_expose_count"
    - "userid_ctr"
    - "article_id"
    - "keywords"
    - "image_count"
    - "doc_title_embed"
    - "docid_history_duration_mean"
    - "docid_history_count"
    - "docid_expose_count"
    - "docid_ctr"
    - "category_level1"
    - "category1_ctr"
    - "category1_popularity"
    - "category_level2"
    - "category1_history_duration_mean"
    - "category2_ctr"
    - "category2_popularity"
    - "category2_history_duration_mean"
    - "expose_hour"
    - "network_env"
    - "refresh_count"
    - "userid_category1_history_count"
    - "userid_category1_ctr"
    - "userid_category1_history_duration_mean"
    - "userid_category2_history_count"
    - "userid_category2_ctr"
    - "userid_category2_history_duration_mean"
  lhuc_feature_columns_name:
    - "device_name"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
din:
  linear_feature_columns:
    - "expose_pos"
    - "expose_hourdiff"
    - "expose_hour"
    - "device_name"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "userid_history_duration_mean"
    - "userid_history_count"
    - "userid_expose_count"
    - "userid_ctr"
    - "docid_history_duration_mean"
    - "docid_history_count"
    - "docid_expose_count"
    - "docid_ctr"
    - "category1_ctr"
    - "category1_popularity"
    - "category1_history_duration_mean"
    - "category2_ctr"
    - "category2_popularity"
    - "category2_history_duration_mean"
    - "userid_category1_history_count"
    - "userid_category1_ctr"
    - "userid_category1_history_duration_mean"
    - "userid_category2_history_count"
    - "userid_category2_ctr"
    - "userid_category2_history_duration_mean"
  dnn_feature_columns:
    - "expose_hourdiff"
    - "user_id"
    - "device_name"
    - "os"
    - "province"
    - "city"
    - "age"
    - "gender"
    - "userid_history_duration_mean"
    - "userid_history_count"
    - "userid_expose_count"
    - "userid_ctr"
    - "article_id"
    - "keywords"
    - "image_count"
    - "doc_title_embed"
    - "docid_history_duration_mean"
    - "docid_history_count"
    - "docid_expose_count"
    - "docid_ctr"
    - "category_level1"
    - "category1_ctr"
    - "category1_popularity"
    - "category_level2"
    - "category1_history_duration_mean"
    - "category2_ctr"
    - "category2_popularity"
    - "category2_history_duration_mean"
    - "expose_hour"
    - "network_env"
    - "refresh_count"
    - "userid_category1_history_count"
    - "userid_category1_ctr"
    - "userid_category1_history_duration_mean"
    - "userid_category2_history_count"
    - "userid_category2_ctr"
    - "userid_category2_history_duration_mean"
  query_feature_columns:
    - "article_id"
    - "category_level1"
    - "category_level2"
  key_feature_columns:
    - "hist_article_id"
    - "hist_category_level1"
    - "hist_category_level2"
  bias_feature_columns:
    - "hist_hourdiff"
  hist_mask_value: 0
  dnn_hidden_units: [200,80]
  dnn_activation: 'relu'
  att_hidden_size: [80,40]
  att_activation: 'sigmoid'
  dnn_dropout: 0
  seed: 1024